### POST test
POST http://localhost:8080/trades
Content-Type: application/json

{
  "stockName": "BTC",
  "amount": 3900,
  "pnl": 120,
  "leverage": 8,
  "positive": true,
  "date": "2026-02-02",
  "description": "Test trade 3 for BTC"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### GET test for login
GET http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "caden@gmail.com",
  "password": "pass123"
}

### GET test for login 2
GET http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "caden2@gmail.com",
  "password": "pass123"
}