spring.application.name=FSMobileBackend
spring.mongodb.host=${SPRING_DATA_MONGODB_HOST}
spring.mongodb.port=${SPRING_DATA_MONGODB_PORT}
spring.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
spring.mongodb.username=${SPRING_DATA_MONGODB_ADMIN}
spring.mongodb.password=${SPRING_DATA_MONGODB_PASS}
spring.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTH}
